<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8nZN5qf' shared service.

return $this->privates['.service_locator.8nZN5qf'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('produit' => function (): \App\Entity\Produits {
    return ($this->privates['.errored..service_locator.8nZN5qf.App\Entity\Produits'] ?? $this->load('getProduitsService.php'));
}));
