<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator._Fzl8mQ.App\Entity\Contrebandier' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator._Fzl8mQ": it references class "App\\Entity\\Contrebandier" but no such service exists.');
