<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.8nZN5qf.App\Entity\Produits' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.8nZN5qf": it references class "App\\Entity\\Produits" but no such service exists.');
