<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\ContrebandierController::delete' => function () {
    return ($this->privates['.service_locator._Fzl8mQ'] ?? $this->load('get_ServiceLocator_Fzl8mQService.php'));
}, 'App\\Controller\\ContrebandierController::edit' => function () {
    return ($this->privates['.service_locator._Fzl8mQ'] ?? $this->load('get_ServiceLocator_Fzl8mQService.php'));
}, 'App\\Controller\\ContrebandierController::show' => function () {
    return ($this->privates['.service_locator._Fzl8mQ'] ?? $this->load('get_ServiceLocator_Fzl8mQService.php'));
}, 'App\\Controller\\ProduitsController::delete' => function () {
    return ($this->privates['.service_locator.8nZN5qf'] ?? $this->load('get_ServiceLocator_8nZN5qfService.php'));
}, 'App\\Controller\\ProduitsController::edit' => function () {
    return ($this->privates['.service_locator.8nZN5qf'] ?? $this->load('get_ServiceLocator_8nZN5qfService.php'));
}, 'App\\Controller\\ProduitsController::show' => function () {
    return ($this->privates['.service_locator.8nZN5qf'] ?? $this->load('get_ServiceLocator_8nZN5qfService.php'));
}, 'App\\Controller\\ContrebandierController:delete' => function () {
    return ($this->privates['.service_locator._Fzl8mQ'] ?? $this->load('get_ServiceLocator_Fzl8mQService.php'));
}, 'App\\Controller\\ContrebandierController:edit' => function () {
    return ($this->privates['.service_locator._Fzl8mQ'] ?? $this->load('get_ServiceLocator_Fzl8mQService.php'));
}, 'App\\Controller\\ContrebandierController:show' => function () {
    return ($this->privates['.service_locator._Fzl8mQ'] ?? $this->load('get_ServiceLocator_Fzl8mQService.php'));
}, 'App\\Controller\\ProduitsController:delete' => function () {
    return ($this->privates['.service_locator.8nZN5qf'] ?? $this->load('get_ServiceLocator_8nZN5qfService.php'));
}, 'App\\Controller\\ProduitsController:edit' => function () {
    return ($this->privates['.service_locator.8nZN5qf'] ?? $this->load('get_ServiceLocator_8nZN5qfService.php'));
}, 'App\\Controller\\ProduitsController:show' => function () {
    return ($this->privates['.service_locator.8nZN5qf'] ?? $this->load('get_ServiceLocator_8nZN5qfService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
