<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW9qMz3T\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW9qMz3T/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerW9qMz3T.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerW9qMz3T\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerW9qMz3T\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'W9qMz3T',
    'container.build_id' => '6827c831',
    'container.build_time' => 1543132176,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerW9qMz3T');
